# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rude Duchy
author: Tomash
author_link: /about
author_description: Losowy nerd z internetu
email: tomekrs@o2.pl
description: > # this means to ignore newlines until "baseurl:"
  Kolejny blog o whisky i tematach pokrewnych, prowadzony przez kompletnego amatora.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rudeduchy.pl" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: 

# Build settings
gems:
  - jekyll-paginate
  - jekyll-sitemap
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compact
